/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 P:\FA24\Dev\Front-end\public\models\african_penguin_spheniscus_demersus_low_poly.glb 
Author: Major (https://sketchfab.com/majorgalah)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/african-penguin-spheniscus-demersus-low-poly-9e59070815fe451d93398e2ebdb9bb92
Title: African penguin (Spheniscus demersus) Low poly
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/african_penguin_spheniscus_demersus_low_poly.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.055}>
          <group name="42301cbc902b498c98796e81d522811ffbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Animal" position={[0, -308.99, -173.11]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
                <group name="Armature" position={[0, -308.99, -173.11]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_6">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_8" position={[0, -308.99, -173.11]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
                    <group name="Object_73" position={[0, -308.99, -173.11]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
                    <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Creature} skeleton={nodes.Object_9.skeleton} />
                    <skinnedMesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.Creature} skeleton={nodes.Object_74.skeleton} />
                  </group>
                </group>
                <group name="Transparent" position={[0, -308.99, -173.11]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/african_penguin_spheniscus_demersus_low_poly.glb')
