/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 P:\FA24\Dev\Front-end\public\models\Sasha.glb 
Author: Mateusz Woliński (https://sketchfab.com/jeandiz)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/sasha-f6030ea6afd049fbb338b6c0ca241d7f
Title: Sasha
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Chatbot(props) {
  const { scene } = useGLTF('./models/Sasha.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.Body} skeleton={nodes.Object_7.skeleton} />
          <skinnedMesh geometry={nodes.Object_180.geometry} material={materials.Body} skeleton={nodes.Object_180.skeleton} />
          <skinnedMesh geometry={nodes.Object_182.geometry} material={materials.Jacket} skeleton={nodes.Object_182.skeleton} />
          <skinnedMesh geometry={nodes.Object_184.geometry} material={materials.Body} skeleton={nodes.Object_184.skeleton} />
          <skinnedMesh geometry={nodes.Object_186.geometry} material={materials.Face} skeleton={nodes.Object_186.skeleton} />
          <skinnedMesh geometry={nodes.Object_188.geometry} material={materials.Body} skeleton={nodes.Object_188.skeleton} />
          <skinnedMesh geometry={nodes.Object_190.geometry} material={materials.Body} skeleton={nodes.Object_190.skeleton} />
          <skinnedMesh geometry={nodes.Object_192.geometry} material={materials.Outline} skeleton={nodes.Object_192.skeleton} />
          <skinnedMesh geometry={nodes.Object_194.geometry} material={materials.Outline} skeleton={nodes.Object_194.skeleton} />
          <skinnedMesh geometry={nodes.Object_196.geometry} material={materials.Outline} skeleton={nodes.Object_196.skeleton} />
          <skinnedMesh geometry={nodes.Object_198.geometry} material={materials.Outline} skeleton={nodes.Object_198.skeleton} />
          <skinnedMesh geometry={nodes.Object_200.geometry} material={materials.Outline} skeleton={nodes.Object_200.skeleton} />
          <skinnedMesh geometry={nodes.Object_202.geometry} material={materials.Outline} skeleton={nodes.Object_202.skeleton} />
          <skinnedMesh geometry={nodes.Object_204.geometry} material={materials.Outline} skeleton={nodes.Object_204.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/Sasha.glb')
