// import React, { useEffect, useMemo } from "react";
// import { useGraph } from "@react-three/fiber";
// import { useGLTF, useFBX, useAnimations } from "@react-three/drei";
// import { SkeletonUtils } from "three-stdlib";

// export default function Chatbot(props) {
//   const { scene, animations } = useGLTF("./models/model.glb"); // Load file GLTF
//   const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]); // Clone scene

//   // Check cấu trúc của SkinnedMesh
//   const { nodes, materials } = useGraph(clone);
//   console.log(nodes, materials);

//   // Load animation
//   const fbx = useFBX("./animations/Typing.fbx");
//   const { actions } = useAnimations(fbx.animations, clone);
//   console.log(actions);

//   useEffect(() => {
//     if (actions["Typing"]) {
//       actions["Typing"].reset().fadeIn(10).play(); // Chạy animation
//     }
//     return () => {
//       if (actions["Typing"]) {
//         actions["Typing"].fadeOut(10); // Ngừng animation
//       }
//     };
//   }, [actions]);

//   return (
//     <group {...props} dispose={null}>
//       {/* Kiểm tra và render SkinnedMesh */}
//       {Object.keys(nodes).map((key) => {
//         const node = nodes[key];
//         if (node.isSkinnedMesh) {
//           return (
//             <skinnedMesh
//               key={key}
//               geometry={node.geometry || null} // Kiểm tra geometry
//               material={node.material || null} // Kiểm tra material
//               skeleton={node.skeleton || null} // Kiểm tra skeleton
//             />
//           );
//         }
//         return null;
//       })}
//     </group>
//   );
// }

// useGLTF.preload("./models/model.glb");
// useFBX.preload("./animations/Pointing.fbx");


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 P:\FA24\LandingPageThreeJS\public\models\model.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useGraph } from '@react-three/fiber'
import { useAnimations, useGLTF, useFBX } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'


export function Chatbot(props) {
  const { scene } = useGLTF('./models/model.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)

  const group = useRef();

  const { animations: PointingAnimation } = useFBX("./animations/Pointing.fbx")

  PointingAnimation[0].name = "Pointing";

  const { actions } = useAnimations(PointingAnimation, group);

  useEffect(() => {
    actions['Pointing'].reset().play()
  }, []);

  return (
    <group {...props} ref={group} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh geometry={nodes.avaturn_body.geometry} material={materials.avaturn_body_material} skeleton={nodes.avaturn_body.skeleton} />
    </group>
  )
}

export default Chatbot;

useGLTF.preload('./models/model.glb')
