/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 P:\FA24\Dev\Front-end\public\models\sad_toaster.glb 
Author: Tasha.Lime (https://sketchfab.com/tasha.lime)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/sad-toaster-9b158486dfa1490eb9157966321283a0
Title: Sad toaster
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Chatbot(props) {
  const { nodes, materials } = useGLTF('./models/sad_toaster.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/sad_toaster.glb')
